InboundNetworkEvents
| where timestamp between (datetime("2024-04-10T00:00:00") .. datetime("2024-04-11T00:00:00"))
| where src_ip has "18.66.52.227"
| where url contains "fluffy"

Consulta la tabla InboundNetworks y especifica la busqueda entre las fechas 10/04/2024 - 11/04/2024 que coincida con todas las solicitudes de origen 18.66.52.227 y que contenga en la columna URL 
el valor fluffy


**************************************************************

Email
| where recipient has "owl-records.com" and link has "betterlyrics4u.com"
